### ISSUE TITLE
Messing up properties in the new tool form

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-frontend#120]
In GitLab by @KlausIllmayer on Oct 11, 2022, 16:10

# 🐛 Bug Report

Under specific circumstances it is not possible to choose from a drop down list (= vocabulary driven property) when trying to create a new tool/service. This happens only when from the prefilled property list some properties are deleted.

## 🤔 Expected Behavior

Choosing from a property drop down list should work.

## 😯 Current Behavior

The drop down list shows values, but it is not possible to choose one resp. you choose one, it shows up in the drop down input field but disappears if you go to the next field.

There is no error visible, also not in the console (tried it out on stage and on develop)

## 🧭 How to reproduce

1. Login on MP
2. Create Tool or service
3. Scroll down to property type "Intended audience"
4. Delete the two property types above the "Intended audience": delete first "Tool Family" and then "Mode of use"
5. Click into "Intended audience" and choose a value e.g. "Public"
6. Go to the next property field "See also", now the value in "Intended audience" disappears

This is the simplest way to reproduce it, but it must have to do with some general problem when using the "delete", e.g., the problem does not show up when only deleting "Mode of use". I discovered the problem when I was supporting entering a new tool. We deleted the properties where we didn't found a value and suddenly it was not possible to choose values from some of the property types. As there is no warning/error, it is very irritating and may result in people not entering data anymore.

---

**Comment by stefanprobst** [comment]
should hopefully be fixed by https://github.com/SSHOC/sshoc-marketplace-frontend/commit/054ee1c918cbb4ee5113b5d863f43d6f6220141f
