### ISSUE TITLE
"My contributed items" does not show approved items to contributors

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-frontend#125]
In GitLab by @KlausIllmayer on Feb 17, 2022, 13:58

When suggesting an item as a contributor, this item will show up in the "My contributed items"-section in the "My account"-part. But when a moderator is approving this item, the item disappears from the "My contributed items"-section, as the moderator is now the "owner" of the item. For a contributor it could be irritating to lose the connection to a contributed item. Imaging spending a lot of time to suggest a new item and then having no single access point where you can see all your contributed items. At least the label "My contributed items" needs to be reviewed for contributors, if we stay with the current approach.

Opinions? @vronk @laureD19 @egray523 @stefanprobst

**Comment by stefanprobst** [comment]
dependent on https://github.com/SSHOC/sshoc-marketplace-backend/issues/168

**Comment by KlausIllmayer** [comment]
This issue can be now handled, as the blocking issue https://github.com/SSHOC/sshoc-marketplace-backend/issues/168 is now solved.

The current contributed items view approach can be now replaced with the endpoint `GET /api/contributed-items`. There you will get all items where a user did perform an activity.
