### ISSUE TITLE
preview workflow - bug

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-frontend#129]
In GitLab by @laureD19 on Nov 16, 2022, 20:07

when creating a workflow and its steps and saving or submitting it, the preview mode does not allow users to see the steps, but only the workflow.

- if the workflow and its steps are saved as draft and a contributor accesses the workflow again via "my draft items", the preview only shows the workflow and the steps are missing.
- if the workflow and its steps are submitted, the moderator only sees the workflow and steps are missing while clicking on the label of the workflow from the "items to moderate" screen.

Experienced by some users today during the sprint and reproduced on stage. Example: https://sshoc-marketplace-stage.acdh-dev.oeaw.ac.at/workflow/lEuWKY/version/48679 

notify also @KlausIllmayer @egray523

**Comment by KlausIllmayer** [comment]
Backend delivers back the values in a [correct way](https://github.com/SSHOC/sshoc-marketplace-backend/issues/161), seems therefore that frontend does not show the steps
