### ISSUE TITLE
recommended fields update in the edit forms

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-frontend#131]
In GitLab by @laureD19 on Nov 16, 2022, 20:51

Based on the first six months of use, recommended fields have been/will be updated soon in the documentation: [gdoc version ](https://docs.google.com/document/d/1g20glV6s7DLmqSYBqDNuIWk-sI1fGZG6KNRQfLDS61Y/edit#bookmark=kix.5m8qxip6zpl1) to prepare the update of the static page https://marketplace.sshopencloud.eu/contribute/metadata-guidelines#metadata-status 

Config of the forms should be updated accordingly.

notify also @KlausIllmayer @egray523

**Comment by laureD19** [comment]
closing this issue as it is now covered by #179 and #180
