### ISSUE TITLE
API documentation - static pages

### ISSUE THREAD

**Issue by laureD19** [SSHOC/sshoc-marketplace-frontend#139]
the CMS access /admin#/ is still connected to Gitlab and leads to the following error: `The authorization server does not support this response type.` when trying to connect.

While waiting for access via Github accounts, I'm preparing materials for update of the static pages [here](https://docs.google.com/document/d/1g20glV6s7DLmqSYBqDNuIWk-sI1fGZG6KNRQfLDS61Y/edit#), and I have a few comments/questions:

- I've collected better quality images to replace the bad ones. 
- @stefanprobst Is it possible to embed videos on static pages? I'd like to add [this one ](https://www.youtube.com/watch?v=4tyZ4vhrM9s)on one of the about pages.
- for the API documentation section ([p.18](https://docs.google.com/document/d/1g20glV6s7DLmqSYBqDNuIWk-sI1fGZG6KNRQfLDS61Y/edit#heading=h.qy6zj6duqkto)), @stefanprobst and @KlausIllmayer , I'd need your review: @stefanprobst because I'm not sure at all about the widget format, although I've tried out some suggestions in the gdoc; @KlausIllmayer to make sure you agree with the use cases described in this section.

@stefanprobst once CMS access is solved, can you tell me again on which instance I should work to implement the changes? I believe the dev one - https://sshoc-marketplace.acdh-dev.oeaw.ac.at/admin#/ -, but I'm not sure anymore

**Comment by stefanprobst** [comment]
you should now be able to sign in via https://marketplace.sshopencloud.eu/admin

published content will be pushed directly to the production deployment.

- it is possible to embed youtube videos via iframe - but i don't think we have a cms editor widget for this currently - easiest would be to copypaste the embed markup from youtube directly in the .md file - or we could steal the Video cms editor widget from dariah campus

**Comment by laureD19** [comment]
Thanks a lot!!

I got an error while trying to publish: "Failed to persist entry: API_ERROR: At least 1 approving review is required by reviewers with write access."

**Comment by stefanprobst** [comment]
ah sorry, removed branch protection, should work now (i hope)

**Comment by laureD19** [comment]
Yes, it works! That's great! Thanks a lot Stefan :)

**Comment by laureD19** [comment]
I was a bit too optimistic too fast! I got some failed jobs for the last two publications. 

The changes are saved on the CMS side, but [I got the same error twice on deployment](https://github.com/SSHOC/sshoc-marketplace-frontend/actions/workflows/build-deploy.yml).

**Comment by stefanprobst** [comment]
that's because of autolinks in mdx. i'll change those.

**Comment by laureD19** [comment]
sorry to bother again...

I'd like to create a new entry in the about pages, but I can't via the CMS. Can I[ add a file directly here](https://github.com/SSHOC/sshoc-marketplace-frontend/tree/main/src/pages/about) or do you prefer to do it? In case the title of the page and in the menu should be "API Documentation" and the position "5".

**Comment by stefanprobst** [comment]
yep, exactly, just add a file in that folder with the `.page.mdx` extension (already did it now for this page).

you can also try enabling adding about pages via cms by changing [this setting](https://github.com/SSHOC/sshoc-marketplace-frontend/blob/main/src/lib/cms/collections/about-pages.ts#L10-L11).

**Comment by stefanprobst** [comment]
could you retitle the issue to reflect what is still missing here? only thing missing is api docs, correct? thanks!

**Comment by laureD19** [comment]
Indeed, only the API documentation still needs to be finalised.

In this doc, ([p.18](https://docs.google.com/document/d/1g20glV6s7DLmqSYBqDNuIWk-sI1fGZG6KNRQfLDS61Y/edit#heading=h.qy6zj6duqkto)), I have a draft that needs your review @stefanprobst and @KlausIllmayer.

- @stefanprobst because I'm not sure at all about the widget format, although I've tried out some suggestions in the gdoc; 
- @KlausIllmayer to make sure you agree with the use cases described in this section.

In the meantime, I'll proceed with a first online version for things that I'm sure about, adding a 'under construction' warning on the top of the page.

**Comment by laureD19** [comment]
Hi @stefanprobst! Thx for opening the cms for the stage instance too. I'm now able to log in to both main and stage CMS.

Nonetheless, I managed to publish content on stage only once. And got failed actions after this one time. Everything seems to work well with the prod/main branch.

My question is: what should I do if I pushed changes to stage, but the action failed, can I push the same changes via the prod CMS. I remember you saying no! How should I proceed then? Thx!

**Comment by stefanprobst** [comment]
we should decide on 1 workflow: either push to `main` (i.e. log into the production instance), which means changes go live on the prod site as soon as the action finished. or only push to stage, and manually merge changes to main (i.e. push to the prod site). otherwise the two branches diverge.

generally speaking though, publishing to stage via cms should work just fine. the most recent stage action points to a syntax error: https://github.com/SSHOC/sshoc-marketplace-frontend/actions/runs/4041810500/jobs/6949917228#step:6:318
