### ISSUE TITLE
display table of contents on about and contribute pages 

### ISSUE THREAD

**Issue by laureD19** [SSHOC/sshoc-marketplace-frontend#141]
The option to display the table of content of a static page based on the Headings doesn't seem to work anymore. even if the option box is ticked in the CMS and headings are present in the page, no table of content is displayed. 

Is that a bug or me not knowing how to properly use it?

**Comment by stefanprobst** [comment]
did the ToC work previously?

**Comment by laureD19** [comment]
I'm pretty sure I saw it already, yes. But I couldn't say when it disappeared.

**Comment by stefanprobst** [comment]
we have been, and still are, extracting table of contents *data*, but according to git history we have never actually displayed that data. it's easy to do, just needs some guidelines for design.

**Comment by stefanprobst** [comment]
added in bb9ecd23b939323e3b5622dc23017b59f0c0604b
