### ISSUE TITLE
Use 404 page for not existing items

### ISSUE THREAD

**Issue by KlausIllmayer** [SSHOC/sshoc-marketplace-frontend#144]
There is a dedicated "404 - Page not found." webpage, if you use a wrong URL that does not exist on the base-URI of marketplace, e.g. https://marketplace.sshopencloud.eu/i-dont-exist

This webpage does not show up, if you have a wrong (or not longer working) URL of one of the items (resp. within the namespace of the items), e.g. try out https://marketplace.sshopencloud.eu/tool-or-service/i-dont-exist. There you get the error message "Something went wrong". Looking into the network analysis I see a 404 returned by backend.

I think it is better to also show the dedicated"404 - Page not found" for not existing items. @laureD19 @stefanprobst do you agree?

**Comment by stefanprobst** [comment]
yes, agreed
