### ISSUE TITLE
Edit Forms - disappering values when special characters are included

### ISSUE THREAD

**Issue by laureD19** [SSHOC/sshoc-marketplace-frontend#171]
Current: When a value (actor, property) suggested in the auto-complete includes a slash, after being selected, if the user clicks somewhere else on the page, the value disappears. It doesn’t prevent submitting or saving items, but leads users to think that they have not selected anything.
![image](https://github.com/SSHOC/sshoc-marketplace-frontend/assets/53609810/566ab8eb-386c-4ee6-aa37-fe4b77dcbef9)

Expected: When selecting a value that includes a slash, the value should be displayed.

@notify @mkrzmr @KlausIllmayer @vronk

**Comment by stefanprobst** [comment]
@tparkola do i need to escape the "/" slash character for `/api/actor-search?q=`?

**Comment by tparkola** [comment]
I would suggest to encode, but as far as I see it is not necessary in this case (parameter).

**Comment by stefanprobst** [comment]
@tparkola i'm asking because when i search for "DARIAH-GR", i get a match:

```bash
curl "http://localhost:8080/api/actor-search?q=DARIAH-GR" | jq
```

returns:

```json
{
  "actors": [
    {
      "affiliations": [],
      "externalIds": [],
      "id": 52,
      "name": "DARIAH-GR / DYAS"
    }
  ],
  "count": 1,
  "hits": 1,
  "page": 1,
  "pages": 1,
  "perpage": 20,
  "q": "DARIAH-GR"
}
```

but when searching for "DARIAH-GR / DYAS" i get none:

```bash
curl "http://localhost:8080/api/actor-search?q=DARIAH-GR+%2F+DYAS" | jq
```

returns:

```json
{
  "actors": [],
  "count": 0,
  "hits": 0,
  "page": 1,
  "pages": 0,
  "perpage": 20,
  "q": "DARIAH-GR / DYAS"
}
```

**Comment by stefanprobst** [comment]
@tparkola ping :point_up:

**Comment by tparkola** [comment]
Ok, then I think it is related to the backend, I did a branch with some fixes, could you please check it (if it helps you)? see https://github.com/SSHOC/sshoc-marketplace-backend/tree/bugfix/SSHOC-171_actor_search_related_improvements

**Comment by stefanprobst** [comment]
@tparkola LGTM :+1: - tested the branch locally, and search for "DARIAH-GR / DYAS" works!
