### ISSUE TITLE
Hide "cite as" property in the item detail view

### ISSUE THREAD

**Issue by laureD19** [SSHOC/sshoc-marketplace-frontend#182]
waiting for a better citation format of the "cite as" property - see #178 - that we will only be able to implement with a fresh ingest of the CLARIN Resource Families - see https://github.com/SSHOC/SSHOMP-Ingest/issues/44 - we need to hide the cite as property from the item detail view interface.

@stefanprobst - is it something you could prioritise? This is very important for the CLARIN users of the MP.

notify @mkrzmr @vronk @kreetrapper @KlausIllmayer - please comment further if I missed something.

**Comment by stefanprobst** [comment]
fixed in https://github.com/SSHOC/sshoc-marketplace-frontend/commit/a2e358f1ed98925d9fbc66fcd812bd0a82d68511
