### ISSUE TITLE
Thumbnails are not shown for related items

### ISSUE THREAD

**Issue by mkrzmr** [SSHOC/sshoc-marketplace-frontend#183]
Current: Default thumbnails are shown for related items, even when the item has a custom thumbnail (See screenshots)

Expected: When item has a custom thumbnail, it should show in the "related items" view

Suggestion: Update frontend to show custom thumbnails for related items

![Image](https://github.com/SSHOC/sshoc-marketplace-frontend/assets/33122848/b9beb819-e51e-49ae-8710-188d48a796a0)
![Image](https://github.com/SSHOC/sshoc-marketplace-frontend/assets/33122848/822ad8a6-7e5c-4023-895b-efc3f4d9ec33)

**Comment by laureD19** [comment]
as far as I remember, this is the result of an agreement to maintain the coherence of the by-default thumbnails approach in the MP. So thumbnails are intentionally only appearing in the item detail view of the item they are attached to, and not in the related items or in the search results, or in the home page for ex.

**Comment by vronk** [comment]
we stay with this as intended behaviour.
