### ISSUE TITLE
UI does not support versions of drafts

### ISSUE THREAD

**Issue by mkrzmr** [SSHOC/sshoc-marketplace-frontend#184]
Situation: User edits a draft and creates a new version of the draft. The new version is successfully created and displayed. Url is something like this: 

https://marketplace.sshopencloud.eu/workflow/Cy8Vyg/version/{NewVersionId}

Issue: In the UI, links to this version of the draft are not updated. If the user closes the page and returns to the MP later, all links will point to the **initial** draft and there is no way for the user to find the latest version.

This is a serious issue for any workshop, where we usually encourage participants to work with drafts.

**Comment by stefanprobst** [comment]
which links are we talking about?

**Comment by laureD19** [comment]
I've tried to reproduce on stage, with a contributor role.
I've created a new tool, and saved it as draft. 
When I then go to "my draft item" I can access the draft and edit it again, the URL was in my case: /tool-or-service/Lh6gZh/version/64302?draft=true

Then, I made new edits and clicked again on save as draft.
I went again in "my draft items" and accessed again the item. This indeed triggers the SAME URL: /tool-or-service/Lh6gZh/version/64302/edit?draft=true - but I can SEE my latest changes.

Then, assuming the contributor submit the item, and a moderator approves it. The item will disappear form the "my draft items" and be visible in the "my contributed items" section.
New edits on this item now approved will create a new version of the items (i.e. Lh6gZh/**version/64304**/edit?draft=true

So links do not update indeed, but changes in the drafts are incremented. Drafts are not versioned, and I vaguely remember we discussed why a long time ago. Exceptions/bugs could be coming from people working in multiple tabs maybe. This would require further testing to identify where changes in drafts are not well recorded/stored/saved.

**Comment by stefanprobst** [comment]
> Drafts are not versioned

yes, intentionally.

**Comment by stefanprobst** [comment]
is there an actual issue where draft data is not saved properly / cannot be retrieved again?

**Comment by vronk** [comment]
seems to behave as expected, not able to reproduce the issue?

potential case (suspicion):
1. create a new item submit a draft => goes to moderation queue, removed from draft queue
2. because draft disappeared in the list, use may think, it got lost and try to create anew.
