### ISSUE TITLE
EOSC Login broken

### ISSUE THREAD

**Issue by mkrzmr** [SSHOC/sshoc-marketplace-frontend#189]
Users can not sign in through EOSC anymore. They are being redirected to https://eosc-portal.eu/

![Screenshot 2024-07-04 at 11-44-00 EOSC Portal](https://github.com/SSHOC/sshoc-marketplace-frontend/assets/33122848/ba41c1c6-59b8-4e62-ac91-639593337cfc)

This is blocks all user sign-ins.

**Comment by stefanprobst** [comment]
added: https://marketplace.sshopencloud.eu/auth/sign-in
