### ISSUE TITLE
simplifying workflow (and steps) edit form

### ISSUE THREAD

**Issue by laureD19** [SSHOC/sshoc-marketplace-frontend#192]
In order to "simplify" the edit form used to create or edit workflows, the following changes - [discussed during the summer 2024](https://docs.google.com/document/d/1ubhYYgOwEezGuCB9ynKu3IDO9PWEN021KM1hv9V3ibY/edit) - can be implemented:

- [x] workflow form: removing `accessibleAt` field 
- [x] workflow form: update the list of recommended properties displayed by default according to #179 
- [x] step form: remove version
- [x] step form: remove accessibleAt
- [x] step form: remove externalIDs
- [ ] step form: in properties, keep only keyword, activities, input format and output format
- [x] step form: remove media

one open question, maybe more for @mkrzmr , @KlausIllmayer , @vronk : initially, and based on SSK data, we thought related items should be added at the level of the steps only, and not to the full workflow, but MP users started to add related items at the level of the workflow. Is it something you think we should restrict (i.e. no related items for a workflow, but only for its steps?)

**Comment by stefanprobst** [comment]
going to merge https://github.com/SSHOC/sshoc-marketplace-frontend/pull/193 now - in case https://github.com/SSHOC/sshoc-marketplace-frontend/issues/192#issuecomment-2367726191 is incorrect please open a new issue.
