### ISSUE TITLE
Multiple links for externalIds

### ISSUE THREAD

**Issue by mkrzmr** [SSHOC/sshoc-marketplace-frontend#197]
I noticed a strange bug where externalIds are duplicated in the frontend:

![Image](https://github.com/user-attachments/assets/b004db4e-b8c5-4bc3-a3bc-a48945856e88)

Every few seconds, when you scroll the page or interact with it (inspect or switch tabs), these three requests are triggered and another set of links appears:

![Image](https://github.com/user-attachments/assets/19819b3a-ea31-45c4-bf6e-0f3ca259af51)

The backend data does **not** change:

![Image](https://github.com/user-attachments/assets/2f6575f3-1d1c-4b23-8b1b-5b1fb9a31ecd)

To make it more complicated, this only works with some entries, for example:

https://marketplace.sshopencloud.eu/training-material/ohl2yg

https://marketplace.sshopencloud.eu/training-material/XxC3xh

**Comment by stefanprobst** [comment]
i think the reason this happens only for some items is that these have contributors with duplicated `externalIds`, e.g:

![Bildschirmfoto_20241107_132752](https://github.com/user-attachments/assets/fa8a39e3-2554-4e68-ba1f-7e67df1992f7)

**Comment by stefanprobst** [comment]
should be fixed now - duplicated data needs to be cleaned up separately.
